"""Renders genealogy.mmd to _includes/genealogy.svg, the chart on the People page.

Mermaid draws the chart once, in headless Chrome, with the site's font (Figtree
300 from Google Fonts), so the boxes fit the text as the site shows it. The page
then includes a plain SVG and loads no chart script.

Usage (from the repository root, with internet access):
    python3 tools/genealogy/render.py /path/to/chrome

Any Chrome or Chromium binary works, e.g. the chrome-headless-shell that
Playwright installs, or Google Chrome itself. Steps are in README.md.
"""
import html
import pathlib
import re
import subprocess
import sys
import tempfile

MERMAID_URL = 'https://cdn.jsdelivr.net/npm/mermaid@12.1.0/dist/mermaid.min.js'
MERMAID_SRI = 'sha384-EbBpjO7rlR6eqZEcG7GaPpyk9H9WrMyPWX4d3KvPYltgt8Z8l0z6R56B1qP40pR4'
FONT_URL = 'https://fonts.googleapis.com/css?family=Figtree:300&display=swap'
SVG_ID = 'genealogy-chart'

# The classic look draws flat boxes; the default look adds drop shadows.
# Styles of the 2 text lines in each box (classes g-name and g-sub in
# genealogy.mmd). Mermaid measures the boxes with these styles and writes them
# into the SVG, so the page needs no extra CSS for them.
THEME_CSS = (
    '.label, .nodeLabel { font-family: "Figtree", sans-serif; font-weight: 300; }'
    '.g-name { font-size: 15px; color: #181c62; }'
    '.g-sub { font-size: 12.5px; color: #6b7079; }'
    # The ellipsis box below Dr. Lee: a larger grey ellipsis, raised from the
    # baseline so it sits in the middle of the box.
    '.g-more { font-size: 22px; color: #6b7079; letter-spacing: 0.08em;'
    ' position: relative; top: -0.2em; }'
)

CONFIG = """{
  startOnLoad: false,
  securityLevel: 'loose',
  theme: 'base',
  look: 'classic',
  fontFamily: '"Figtree", sans-serif',
  themeCSS: %s,
  themeVariables: {
    fontFamily: '"Figtree", sans-serif',
    fontSize: '15px',
    lineColor: '#9aa0aa',
    primaryTextColor: '#181c62',
    primaryColor: '#ffffff',
    primaryBorderColor: '#dadde3'
  },
  flowchart: {
    htmlLabels: true,
    curve: 'linear',
    nodeSpacing: 28,
    rankSpacing: 34,
    padding: 10,
    wrappingWidth: 400,
    useMaxWidth: true
  }
}"""

PAGE = """<!doctype html>
<html><head><meta charset="utf-8">
<link rel="stylesheet" href="%(font)s">
<script src="%(mermaid)s" integrity="%(sri)s" crossorigin="anonymous"></script>
</head><body>
<pre id="src">%(src)s</pre>
<pre id="out">not rendered</pre>
<script>
(async () => {
  await document.fonts.load('300 15px Figtree');
  await document.fonts.load('300 12.5px Figtree');
  mermaid.initialize(%(config)s);
  const result = await mermaid.render('%(id)s', document.getElementById('src').textContent);
  document.getElementById('out').textContent = result.svg;
})().catch((e) => { document.getElementById('out').textContent = 'ERROR ' + e; });
</script>
</body></html>
"""


def main():
    if len(sys.argv) != 2:
        sys.exit('Usage: python3 tools/genealogy/render.py /path/to/chrome')
    chrome = sys.argv[1]
    here = pathlib.Path(__file__).resolve().parent
    source = (here / 'genealogy.mmd').read_text(encoding='utf-8')
    out_path = here.parent.parent / '_includes' / 'genealogy.svg'

    page = PAGE % {
        'font': FONT_URL, 'mermaid': MERMAID_URL, 'sri': MERMAID_SRI,
        'src': html.escape(source), 'config': CONFIG % repr(THEME_CSS), 'id': SVG_ID,
    }
    with tempfile.TemporaryDirectory() as tmp:
        page_path = pathlib.Path(tmp) / 'render.html'
        page_path.write_text(page, encoding='utf-8')
        dom = subprocess.run(
            [chrome, '--headless', '--no-sandbox', '--disable-gpu', '--virtual-time-budget=30000',
             '--dump-dom', page_path.as_uri()],
            capture_output=True, text=True, timeout=180, check=False).stdout

    match = re.search(r'<pre id="out">(.*?)</pre>', dom, re.S)
    if not match:
        sys.exit('render.py: Chrome returned no page. Check the Chrome path.')
    svg = html.unescape(match.group(1)).strip()
    if not svg.startswith('<svg'):
        sys.exit('render.py: Mermaid did not render: ' + svg[:300])

    # Box corners: 2px, as on the rest of the site.
    svg = re.sub(r'(<rect class="basic label-container")', r'\1 rx="2" ry="2"', svg)
    header = ('<!-- Generated by tools/genealogy/render.py from tools/genealogy/genealogy.mmd. '
              'Do not edit by hand. -->\n')
    out_path.write_text(header + svg + '\n', encoding='utf-8', newline='\r\n')
    print('render.py: wrote %s (%d bytes)' % (out_path, len(svg)))


if __name__ == '__main__':
    main()
